(defun color-theme-nightingale ()
  "Color theme by Altxwally, port from http://www.winterdom.com/weblog/2007/09/11/NightingaleAVS2005ColorScheme.aspx. Created 2009-03-05"
  (interactive)
  (color-theme-install
   '(color-theme-nightingale
     ((background-color . "gray20")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "gray20")
      (foreground-color . "#C7D4E2")
      (mouse-color . "sienna1"))
     (default ((t (:background "black" :foreground "#FEF1A9"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "black" :foreground "white"))))
     (region ((t (:foreground "cyan" :background "dark cyan"))))
     (font-lock-builtin-face ((t (:foreground "#FEF1A9"))))
     (font-lock-comment-face ((t (:foreground "#FF80C0"))))
     (font-lock-constant-face ((t (:foreground "#00CCFF"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:foreground "#40C4FF" :bold t))))
     (font-lock-keyword-face ((t (:foreground "#fab732"))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))
     (font-lock-string-face ((t (:foreground "#60FF3C"))))
     (font-lock-type-face ((t (:foreground "#40C4FF"))))
     (font-lock-variable-name-face ((t (:foreground "#FEF1A9"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (highlight ((t (:background "darkolivegreen"))))
     (highline-face ((t (:background "SeaGreen"))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (toolbar ((t (nil))))
     (underline ((nil (:underline nil))))
     (zmacs-region ((t (:background "snow" :foreground "blue")))))))