
(global-set-key [?\C--] 'hippie-expand)
(global-set-key (kbd "<f1>") 'copy-region-as-kill)
(global-set-key (kbd "<f2>") 'ido-switch-buffer)
;; (global-set-key (kbd "<f3>") 'find-file-other-window)
(global-set-key (kbd "<S-f3>") 'find-file-other-frame)
(global-set-key (kbd "<f4>") 'speedbar)
(global-set-key (kbd "<C-f4>")  'sr-speedbar-open)
(global-set-key (kbd "<f5>") 'replace-regexp)
(global-set-key (kbd "<f6>") 'replace-string)
(global-set-key (kbd "<f7>") 'regexp-builder)
(global-set-key (kbd "<C-f7>") 'twit-post-region)
(global-set-key (kbd "<f8>") 'toggle-truncate-lines)
(global-set-key (kbd "<C-f9>") 'menu-bar-mode)
(global-set-key (kbd "<f10>") 'linum-mode)
(global-set-key (kbd "<C-f11>") 'make-frame-command)
(global-set-key (kbd "<C-tab>") 'dabbrev-expand)
(global-set-key "\C-c\C-p" 'sgml-tag)
(global-set-key "\C-c\C-o" 'shrink-window)
(global-set-key "\C-c\C-k" 'copy-region-as-kill)
(global-set-key "\C-c\C-v" 'x-clipboard-yank)
(global-set-key "\C-ce" 'ido-switch-buffer)
(global-set-key (kbd "<C-f10>")  'dame-shell)
(global-set-key (kbd "<M-f10>")  'rename-buffer)
;;(global-set-key (kbd "<f12>")  'anthy-mode)
(global-set-key (kbd "<f12>")  'org-clock-goto)
(global-set-key (kbd "<M-prior>") 'previous-error)
(global-set-key (kbd "<M-next>")  'next-error)
(global-set-key (kbd "<C-f3>")  'rgrep)
(global-set-key (kbd "<C-f2>")  'choche-start-mysql)
;; (global-set-key (kbd "<C-f2>")  'wally-start-mysql)
(global-set-key (kbd "<C-f1>")  'rails/goto-associated)
(global-set-key (kbd "<S-f1>")  'twitter-get-friends-timeline)
(global-set-key (kbd "<S-f2>")  'ido-switch-buffer-other-window)
(global-set-key (kbd "<S-f4>")  'speedbar-update-contents)
(global-set-key (kbd "<S-f8>")  'rails/console)
;; (global-set-key (kbd "<C-f11>")  'undo)
(global-set-key (kbd "<C-S-f2>")  'ido-switch-buffer-other-frame)
(global-set-key (kbd "<S-f11>")  'text-scale-decrease)
(global-set-key (kbd "<S-f12>")  'text-scale-increase)
(global-set-key (kbd "<M-f12>")  'other-frame)
(windmove-default-keybindings 'meta)
;; (global-set-key "\C-c\C-a" 'wally-comment-macro2)
(global-set-key "\C-c\C-a" 'wally-comment-indent-line)
(global-set-key "\C-c=" 'hashRocket)
(global-set-key "\C-c\C-e" 'wally-select-line-macro)
(global-set-key (kbd "<M-f11>")  'indent-whole-buffer)
(global-set-key "\C-cw" 'kill-this-buffer)
(global-set-key (kbd "<C-f12>") 'kill-this-buffer)
(global-set-key "\C-z" 'undo)
(global-set-key "\C-cm" 'filetemignon)
(global-set-key "\C-cs" 'wally-select-line)
(global-set-key "\C-t" 'other-frame)
(global-set-key "\C-cl" 'choche-magical-quotes)
(global-set-key (kbd "C-c 2") 'swap-windows)
(global-set-key (kbd "C-c N") 'wally-diccionario-es)
(global-set-key (kbd "<C-prior>")  'previous-buffer)
(global-set-key (kbd "<C-next>")  'next-buffer)
(global-set-key (kbd "<S-f2>")  'hacker-news)
(global-set-key [f11] 'fullscreen)
(global-set-key (kbd "<M-f6>")  'django-html-mode)
(global-set-key (kbd "<S-f9>")  'twit-search)
(global-set-key (kbd "<C-f5>")  'hs-minor-mode)
(global-set-key (kbd "<C-f6>")  'auto-complete-mode)
(global-set-key (kbd "<S-f1>")  'twittering-friends-timeline)
(global-set-key "\C-co" 'wally-insert-org-block)
(global-set-key "\C-c¥" 'wally-insert-backslash)
(global-set-key (kbd "<C-s-f10>")  'wally-fix-buffer-settings)

(add-hook 'org-mode-hook
          '(lambda ()
	     (local-set-key (kbd "<C-tab>") 'dabbrev-expand)
             ))

(provide 'wallemacs-keybindings)