
(defun color-theme-casi-django ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/567383/"
  (interactive)
  (color-theme-install
   '(inspiration-567383
     ((background-color . "#00180F")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#73F864"))))
     (font-lock-constant-face ((t (:foreground "#CC735A"))))
     (font-lock-builtin-face ((t (:foreground "#F9B136"))))
     (font-lock-function-name-face ((t (:foreground "#BDFFD7"))))
     (font-lock-variable-name-face ((t (:foreground "#A6E687"))))
     (font-lock-keyword-face ((t (:foreground "#FE6152"))))
     (font-lock-string-face ((t (:foreground "#DCC4A0"))))
     (font-lock-doc-string-face ((t (:foreground "#DCC4A0"))))
     (font-lock-type-face ((t (:foreground "#FFCDD6"))))
     )))

(provide 'color-theme-casi-django)